### ISSUE TITLE
Get followers not working

### ISSUE THREAD

**Issue by AlexPaiva** [stanfordio/truthbrush#15]
When I try scraping followers I get:

`line 113, in _get_paginated
    next_link = resp.links.get("next", {}).get("url")
AttributeError: 'Response' object has no attribute 'links'`

**Comment by lxcode** [comment]
This is a casualty of recent changes to fix the rest of the functionality — however, followers/following functionality is fundamentally broken within Truth Social itself, only returning 40 results in the app or via the API.

**Comment by AlexPaiva** [comment]
I actually managed to fix it myself eventually, but now for some reason it won't even start the API or show any info on console out of nowhere and I can't seem to figure out why. I will send a PR with the fix soon aswell, any idea why it stopped working?

**Comment by AlexPaiva** [comment]
> This is a casualty of recent changes to fix the rest of the functionality — however, followers/following functionality is fundamentally broken within Truth Social itself, only returning 40 results in the app or via the API.

Actually after further digging basically Truth Social is returning a .html reply with 'Access denied
You do not have access to truthsocial.com.

The site owner may have set restrictions that prevent you from accessing the site.

Ray ID: 7ce29384fd8e54db
Timestamp: 2023-05-28 01:03:09 UTC
Your IP address: -----------
Requested URL: truthsocial.com/api/v1/statuses/110322455665368631/favourited_by
Error reference number: 1020
Server ID: FL_341F24
User-Agent: TruthSocial/151 CFNetwork/1406.0.4 Darwin/22.4.0'


Any way you can check if it's the user agent or something related that changed?

**Comment by lxcode** [comment]
Made some changes to the user-agent and request handling, and it looks good now.

**Comment by lxcode** [comment]
Unfortunately I can't replicate that behavior — the search endpoint, suggestions, etc are working for me. Perhaps it dislikes something about the IP you're coming from or the account you're authenticated with?

**Comment by AlexPaiva** [comment]
> Unfortunately I can't replicate that behavior — the search endpoint, suggestions, etc are working for me. Perhaps it dislikes something about the IP you're coming from or the account you're authenticated with?

Still giving the error even with a fresh pull of git.

To replicate:

Create end point in the api.py:
```
def get_posti(self, post_id: int = 50) -> dict:
        """Return a list of suggested users to follow."""
        self.__check_login()
        params = {
            "limit": 10000000,
            "max_id": None
        }
        return self._get_paginated(f"/v1/statuses/{post_id}/favourited_by")
```

Then call it using (providing the post ID: https://truthsocial.com/@JackPosobiec/posts/110322455665368631:
```
followers = api.get_posti('110322455665368631')
  for follower in followers:
      for mini in follower:
         print(str(mini))
```

Also, the get_paginated I was using previously was this one:

```
def _get_paginated(self, url: str, params: dict = None, resume: str = None) -> Any:
        next_link = API_BASE_URL + url

        if resume is not None:
            next_link += f"?max_id={resume}"

        while next_link is not None:
            resp = self._make_session().get(
                next_link,
                params=params,
                verify=False,
                proxies=proxies,
                headers={
                    "Authorization": "Bearer " + self.auth_id,
                    "User-Agent": USER_AGENT,
                },
            )

            with open('response.html', 'w', encoding='utf-8') as file:
                file.write(str(resp.text))

            try:
                yield resp.json()
            except:
                continue

            next_link = resp.headers.get("Link")
            if next_link:
                next_link = next_link.split(';')[0].strip('<>')
            else:
                next_link = None
            logger.info(f"Next: {next_link}, resp: {resp}, headers: {resp.headers}")
            #yield resp.json()

            # Will also sleep
            self._check_ratelimit(resp)
```

And all you get is a HTML reply with error code, tried multiple IPs and accounts, very strage, can you give me a hand on this?

**Comment by lxcode** [comment]
Please give a try to the version of _get_paginated in the most recent commit.

**Comment by AlexPaiva** [comment]
I did! Same error, can you try it yourself with the "get_posti" function?

**Comment by lxcode** [comment]
Sounds good, thanks!
