### ISSUE TITLE
How to get a group id?

### ISSUE THREAD

**Issue by s2t2** [stanfordio/truthbrush#42]
We can use the `suggested_groups` method to get information about groups, including their unique identifiers.

However how can we get the identifier of any group if we know it's name or slug?

Trying to get the group id for use with the `group_posts` method.

**Comment by s2t2** [comment]
Oh awesome, you can use the `search` method with a searchtype of "groups". I had been trying "group". This isn't documented anywhere! We should document this. Will add some docstring in #41

**Comment by lxcode** [comment]
Thanks! It is in the readme fwiw, but if you're using it as an API I can see why that would be missed.
